set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property -dict { PACKAGE_PIN A18   IOSTANDARD LVCMOS33 } [get_ports out_bit]
set_property PACKAGE_PIN B18 [get_ports in_bit]
set_property IOSTANDARD LVCMOS33 [get_ports in_bit]

#set_property PACKAGE_PIN V17 [get_ports {data[0]}]
#set_property PACKAGE_PIN V16 [get_ports {data[1]}]
#set_property PACKAGE_PIN W16 [get_ports {data[2]}]
#set_property PACKAGE_PIN W17 [get_ports {data[3]}]
#set_property PACKAGE_PIN W15 [get_ports {data[4]}]
#set_property PACKAGE_PIN V15 [get_ports {data[5]}]
#set_property PACKAGE_PIN V14 [get_ports {data[6]}]
#set_property PACKAGE_PIN W13 [get_ports {data[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {showstates[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {showstates[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {showstates[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {showstates[0]}]
#set_property PACKAGE_PIN L1 [get_ports {showstates[3]}]
#set_property PACKAGE_PIN P1 [get_ports {showstates[2]}]
#set_property PACKAGE_PIN N3 [get_ports {showstates[1]}]
#set_property PACKAGE_PIN P3 [get_ports {showstates[0]}]
#set_property PACKAGE_PIN W5 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property PACKAGE_PIN R2 [get_ports reset]
#set_property PACKAGE_PIN T1 [get_ports start]
#set_property IOSTANDARD LVCMOS33 [get_ports start]
#set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property IOSTANDARD LVCMOS33 [get_ports done]
#set_property IOSTANDARD LVCMOS33 [get_ports output]

#set_property PACKAGE_PIN V3 [get_ports done]
#set_property PACKAGE_PIN V13 [get_ports output]